version: 1.9

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false